meta_product_name: "The Cabbage Leaf"
meta_title: "The Cabbage Leaf - Pansez l'actualité"
meta_description: "Un concentré de bonnes nouvelles"
meta_image: "LOGO_theCabbageLeaf-1200x630px-14.png" # should exist in `app/assets/images/`
twitter_account: "@product_twitter_account"   # required for Twitter Cards